// check-release-safety-case.ts
//
// Per-release safety-case guard (Blueprint Part II #55).
//
// A RELEASE-TAGGED build must carry a completed safety case at
// docs/releases/<release>.safety-case.md (generated by
// scripts/src/release/generateSafetyCase.ts, then filled in by a human).
// This guard refuses the build when the document is missing, still carries a
// TBD_REQUIRED placeholder, lacks a required section, or was generated at a
// DIFFERENT commit than the one being released.
//
// WHAT COUNTS AS A RELEASE BUILD (explicit, no guessing):
//   1. env ARX_RELEASE_TAG is set (the deploy pipeline names the release), or
//   2. a git tag matching /^v\d/ or /^release[-/]/ points at HEAD.
// Anything else is a development build and passes with a note — the guard
// must never make ordinary commits need release paperwork, or the paperwork
// gets faked. Git being unavailable resolves to "not a release build" for
// case 2 (a note, not a violation): this guard gates RELEASES, and a release
// pipeline always has git; case 1 needs no git at all.
//
// Green CI still never grants live authority (Article IV). This is a floor
// for tagging a release, not a grant of anything.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import type { CheckResult } from "./_lib.js";
import { ROOT } from "./_lib.js";
import { analyzeSafetyCase } from "../release/safetyCase.js";

export const RELEASES_DIR = "docs/releases";
const RELEASE_TAG_RE = /^(v\d|release[-/])/;

export interface ReleaseContext {
  /** null = not a release build. */
  releaseId: string | null;
  headCommit: string | null;
  notes: string[];
}

/** Resolve whether THIS build is a release build. Explicit sources only. */
export function resolveReleaseContext(
  env: Record<string, string | undefined>,
  gitRunner: (args: string[]) => string | null,
): ReleaseContext {
  const notes: string[] = [];
  const envTag = env["ARX_RELEASE_TAG"]?.trim();
  const headCommit = gitRunner(["rev-parse", "HEAD"]);

  if (envTag) {
    return { releaseId: envTag, headCommit, notes: [`release build declared by ARX_RELEASE_TAG=${envTag}`] };
  }
  const tagsRaw = gitRunner(["tag", "--points-at", "HEAD"]);
  if (tagsRaw === null) {
    notes.push("git unavailable and ARX_RELEASE_TAG unset — treated as a development build");
    return { releaseId: null, headCommit, notes };
  }
  const releaseTags = tagsRaw
    .split("\n")
    .map((t) => t.trim())
    .filter((t) => RELEASE_TAG_RE.test(t));
  if (releaseTags.length === 0) {
    notes.push("no release tag points at HEAD and ARX_RELEASE_TAG unset — development build, no safety case required");
    return { releaseId: null, headCommit, notes };
  }
  notes.push(`release tag(s) at HEAD: ${releaseTags.join(", ")}`);
  return { releaseId: releaseTags[0]!, headCommit, notes };
}

/** Pure core: given a resolved context and a file reader, decide. */
export function analyzeReleaseSafetyCase(
  ctx: ReleaseContext,
  readDoc: (relPath: string) => string | null,
): { violations: string[]; notes: string[] } {
  if (!ctx.releaseId) return { violations: [], notes: ctx.notes };

  const docPath = `${RELEASES_DIR}/${ctx.releaseId}.safety-case.md`;
  const content = readDoc(docPath);
  if (content === null) {
    return {
      violations: [
        `release build "${ctx.releaseId}" has no safety case at ${docPath} — generate it ` +
          `(pnpm --filter @workspace/scripts run release:safety-case -- --release ${ctx.releaseId}), ` +
          "fill in every section, and commit it BEFORE tagging",
      ],
      notes: ctx.notes,
    };
  }
  const violations = analyzeSafetyCase(content, {
    release: ctx.releaseId,
    headCommit: ctx.headCommit,
  }).map((v) => `${docPath}: ${v}`);
  return { violations, notes: ctx.notes };
}

export function checkReleaseSafetyCase(): CheckResult {
  const gitRunner = (args: string[]): string | null => {
    try {
      return execFileSync("git", args, { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
    } catch {
      return null;
    }
  };
  const ctx = resolveReleaseContext(process.env, gitRunner);
  const { violations, notes } = analyzeReleaseSafetyCase(ctx, (relPath) => {
    try {
      return readFileSync(join(ROOT, relPath), "utf8");
    } catch {
      return null;
    }
  });
  return { name: "release-safety-case", ok: violations.length === 0, violations, notes };
}
