// Run summary card for a backtest run.
//
// HONESTY (audit rank 68): this was titled "AI review" with a "Refresh review"
// button. No model is involved — the text is `summarizeBacktest()`, a pure
// deterministic template over the run's stored metrics, and the run's rows are
// immutable, so the button provably could not change a single character. The
// card now says what it is, and the button is gone.

import { useQuery } from "@tanstack/react-query";

export function AIBacktestReviewCard({ runId }: { runId: number | null }) {
  const { data } = useQuery<{ aiSummary: string | null; isVerified?: string; status?: string }>({
    queryKey: ["backtest-run", runId],
    queryFn: async () => {
      const r = await fetch(`/api/backtest-runs/${runId}`);
      if (!r.ok) throw new Error("failed");
      return r.json();
    },
    enabled: runId != null,
  });
  if (!runId) return null;
  return (
    <div className="space-y-2 rounded-lg border border-border bg-muted/40 p-4">
      <header className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-foreground">Run summary</h3>
      </header>
      <p className="rounded border border-border bg-background/40 p-3 text-xs text-txt-secondary">
        {data?.aiSummary ?? "No summary stored for this run."}
      </p>
      <p className="text-[10px] text-txt-muted">
        Generated by a fixed template from this run&apos;s stored metrics — no model reads
        this run, and the text cannot change while the run&apos;s trades are unchanged.
        Past performance does not guarantee future results.
      </p>
    </div>
  );
}
