// Capability #28 — the watchdog's ALERT PATH.
//
// The watchdog's DB session is read-only, so it cannot write a notification
// itself. It delivers findings to the app's notification service over HTTP:
//
//   watchdog process ──POST /api/watchdog/alerts──▶ api-server
//                                                    └─▶ createNotification()
//                                                          └─▶ /api/me/notifications
//                                                              + web push
//
// That is the SAME service the product already uses (the one campaign-8
// front G repointed the Alert Preferences UI at), not a second silo.
//
// THE HONESTY PROBLEM THIS MODULE EXISTS TO SOLVE
// The one moment the alert path is most needed — the main app is down — is
// exactly the moment the primary leg cannot work. So delivery NEVER returns a
// bare boolean and NEVER throws: it returns a typed `AlertDelivery` naming
// which leg ran and why it failed. The caller reports the degraded state
// (`alert_delivery_degraded`) instead of assuming the owner was told. A
// swallowed delivery failure would be a silent, confident lie.
//
// Pure transport: no `pg`, no `@workspace/db`, no app import. `fetch` is
// injectable so the offline tests exercise every branch without a socket.

import { type WatchdogAlertEnvelope } from "./watchdogAlertEnvelope.js";

export type AlertDelivery =
  /** The app accepted the envelope and reported how many notifications it raised. */
  | { leg: "app"; status: "delivered"; notificationsRaised: number | null }
  /** The app was reachable but refused (bad/absent token, malformed body, ingest disabled). */
  | { leg: "app"; status: "refused"; httpStatus: number; reason: string }
  /** The app could not be reached at all — the case the watchdog exists for. */
  | { leg: "app"; status: "unreachable"; reason: string }
  /** No ingest URL/token configured — an owner press that has not happened yet. */
  | { leg: "app"; status: "not_configured"; reason: string }
  /** Secondary operator webhook (optional, independent of the app). */
  | { leg: "webhook"; status: "delivered" }
  | { leg: "webhook"; status: "refused"; httpStatus: number }
  | { leg: "webhook"; status: "unreachable"; reason: string }
  | { leg: "webhook"; status: "not_configured"; reason: string };

export interface AlertSinkConfig {
  /** Full URL of the app ingest endpoint, e.g. https://host/api/watchdog/alerts */
  ingestUrl: string | null;
  /**
   * Shared secret presented as `Authorization: Bearer <token>`.
   * NEVER generated by this code and never logged — the owner sets it on both
   * sides (see docs/WATCHDOG_DEPLOYMENT.md, the owner-press list).
   */
  ingestToken: string | null;
  /** Optional independent operator webhook (Slack/ntfy/etc). */
  webhookUrl: string | null;
  timeoutMs: number;
}

export const WATCHDOG_DELIVERY_TIMEOUT_MS = 8_000;

export function alertSinkConfigFromEnv(env: NodeJS.ProcessEnv): AlertSinkConfig {
  const raw = env.ARX_WATCHDOG_ALERT_INGEST_URL ?? null;
  const timeout = Number(env.ARX_WATCHDOG_DELIVERY_TIMEOUT_MS);
  return {
    ingestUrl: raw && raw.trim().length > 0 ? raw.trim() : null,
    ingestToken: env.ARX_WATCHDOG_INGEST_TOKEN && env.ARX_WATCHDOG_INGEST_TOKEN.length > 0 ? env.ARX_WATCHDOG_INGEST_TOKEN : null,
    webhookUrl: env.ARX_WATCHDOG_WEBHOOK_URL && env.ARX_WATCHDOG_WEBHOOK_URL.length > 0 ? env.ARX_WATCHDOG_WEBHOOK_URL : null,
    timeoutMs: Number.isFinite(timeout) && timeout >= 1_000 ? timeout : WATCHDOG_DELIVERY_TIMEOUT_MS,
  };
}

export type FetchLike = (url: string, init: {
  method: string;
  headers: Record<string, string>;
  body: string;
  signal?: AbortSignal;
}) => Promise<{ ok: boolean; status: number; text: () => Promise<string> }>;

async function post(
  fetchImpl: FetchLike,
  url: string,
  headers: Record<string, string>,
  body: unknown,
  timeoutMs: number,
): Promise<{ kind: "response"; ok: boolean; status: number; text: string } | { kind: "error"; reason: string }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetchImpl(url, {
      method: "POST",
      headers: { "content-type": "application/json", ...headers },
      body: JSON.stringify(body),
      signal: controller.signal,
    });
    let text = "";
    try { text = (await res.text()).slice(0, 400); } catch { text = ""; }
    return { kind: "response", ok: res.ok, status: res.status, text };
  } catch (err) {
    // Includes DNS failure, connection refused, TLS failure and our own abort.
    return { kind: "error", reason: err instanceof Error ? err.message : String(err) };
  } finally {
    clearTimeout(timer);
  }
}

/** Never throws. Returns one result per leg, in order: app first, webhook second. */
export async function deliverAlert(
  envelope: WatchdogAlertEnvelope,
  config: AlertSinkConfig,
  fetchImpl: FetchLike,
): Promise<AlertDelivery[]> {
  const results: AlertDelivery[] = [];

  // ── Leg 1: the product's notification service ────────────────────────────
  if (!config.ingestUrl) {
    results.push({ leg: "app", status: "not_configured", reason: "ARX_WATCHDOG_ALERT_INGEST_URL is unset — findings reach the owner only as logs" });
  } else if (!config.ingestToken) {
    // Fail closed rather than POST unauthenticated: the endpoint would refuse
    // anyway, and an unauthenticated attempt is noise, not an alert.
    results.push({ leg: "app", status: "not_configured", reason: "ARX_WATCHDOG_INGEST_TOKEN is unset — the owner must set the same value on both sides" });
  } else {
    const r = await post(fetchImpl, config.ingestUrl, { authorization: `Bearer ${config.ingestToken}` }, envelope, config.timeoutMs);
    if (r.kind === "error") {
      results.push({ leg: "app", status: "unreachable", reason: r.reason });
    } else if (!r.ok) {
      results.push({ leg: "app", status: "refused", httpStatus: r.status, reason: extractReason(r.text) });
    } else {
      results.push({ leg: "app", status: "delivered", notificationsRaised: extractRaised(r.text) });
    }
  }

  // ── Leg 2: independent operator webhook (survives the app being dead) ────
  if (!config.webhookUrl) {
    results.push({ leg: "webhook", status: "not_configured", reason: "ARX_WATCHDOG_WEBHOOK_URL is unset" });
  } else if (envelope.findings.length > 0) {
    const r = await post(fetchImpl, config.webhookUrl, {}, {
      source: envelope.source,
      instanceId: envelope.instanceId,
      at: envelope.atIso,
      passVerdict: envelope.passVerdict,
      findings: envelope.findings.map((f) => ({ key: f.key, severity: f.severity, message: f.message })),
    }, config.timeoutMs);
    if (r.kind === "error") results.push({ leg: "webhook", status: "unreachable", reason: r.reason });
    else if (!r.ok) results.push({ leg: "webhook", status: "refused", httpStatus: r.status });
    else results.push({ leg: "webhook", status: "delivered" });
  }

  return results;
}

function extractReason(text: string): string {
  try {
    const o = JSON.parse(text) as Record<string, unknown>;
    return typeof o.error === "string" ? o.error : typeof o.reason === "string" ? o.reason : "unspecified";
  } catch { return "unspecified"; }
}

function extractRaised(text: string): number | null {
  try {
    const o = JSON.parse(text) as Record<string, unknown>;
    return typeof o.notificationsRaised === "number" ? o.notificationsRaised : null;
  } catch { return null; }
}

/**
 * True when the operator was NOT reached through the product path this pass.
 * The watchdog logs `alert_delivery_degraded` on this, so "we alerted" is
 * never assumed from an attempt.
 */
export function deliveryIsDegraded(results: readonly AlertDelivery[]): boolean {
  const app = results.find((r) => r.leg === "app");
  return app === undefined || app.status !== "delivered";
}

/** A short, secret-free summary safe to put in a log line. */
export function summariseDelivery(results: readonly AlertDelivery[]): string {
  return results.map((r) => `${r.leg}:${r.status}`).join(",");
}
