// Shadow Predictions — persistent store for shadow mode decisions.
//
// SAFETY:
//   - OBSERVATION ONLY. Never places trades, never touches MT5 bridge,
//     never modifies canPlaceTrades or any live-trading gate.
//   - Rows are immutable once written; outcome fields are updated in-place
//     when the market resolves the prediction.
//   - No broker credentials, no account numbers, no live order IDs stored.
//   - userId is nullable — system-wide shadow decisions have no user.

import {
  pgTable, serial, integer, text, real, boolean,
  timestamp, index,
} from "drizzle-orm/pg-core";

export const shadowPredictionsTable = pgTable("shadow_predictions", {
  id:            serial("id").primaryKey(),
  shadowId:      text("shadow_id").notNull(),          // matches in-memory ShadowDecision.id

  // ── Source ──────────────────────────────────────────────────────────────
  // scanner = auto-generated by shadow mode scanner loop
  // ruby_chat = Ruby explicitly predicted direction in a conversation
  source:        text("source").notNull().default("scanner"), // scanner | ruby_chat

  userId:        integer("user_id"),                   // null = system-wide prediction

  // ── Prediction ───────────────────────────────────────────────────────────
  symbol:        text("symbol").notNull(),
  timeframe:     text("timeframe").notNull().default("M15"),
  strategy:      text("strategy").notNull().default(""),
  marketCondition: text("market_condition"),
  sessionLabel:  text("session_label"),               // asian|london|overlap|newyork

  action:        text("action").notNull(),             // BUY | SELL | WAIT
  entryPrice:    real("entry_price"),
  stopLoss:      real("stop_loss"),
  takeProfit:    real("take_profit"),

  confidence:    real("confidence").notNull().default(0),  // 0-100
  opportunity:   real("opportunity").notNull().default(0),
  sniperScore:   real("sniper_score").notNull().default(0),
  grade:         real("grade").notNull().default(0),

  reason:        text("reason"),
  reasonToAvoid: text("reason_to_avoid"),

  rgApproved:    boolean("rg_approved").notNull().default(false),
  rgLevel:       text("rg_level"),
  rgHardBlocks:  text("rg_hard_blocks"),              // JSON array as text

  // ── R7 step 4 — feature provenance (research/replay reproducibility) ──────
  // featureSetId pins WHICH shared feature engine version (lib/features
  // FEATURE_SET_ID, e.g. "fset_v1") ran when the decision was made;
  // featureSnapshot is the EXACT FeatureSnapshot it saw (JSON as text, same
  // convention as rgHardBlocks) — either the full FeatureVector or an honest
  // INSUFFICIENT_DATA / LOOKAHEAD_REFUSED refusal. Both nullable + additive:
  // pre-R7 rows read as null (their assumptions were never recorded — an
  // honest UNKNOWN, never backfilled).
  // MIGRATION IMPLICATION: two additive nullable columns — plain
  // `ALTER TABLE shadow_predictions ADD COLUMN` via drizzle-kit, no backfill,
  // no rewrite, existing readers/writers unaffected.
  featureSetId:    text("feature_set_id"),
  featureSnapshot: text("feature_snapshot"),          // JSON FeatureSnapshot as text

  predictedAt:   timestamp("predicted_at", { withTimezone: true }).notNull().defaultNow(),
  expiresAt:     timestamp("expires_at", { withTimezone: true }),

  // ── Outcome (filled when resolved) ───────────────────────────────────────
  status:        text("status").notNull().default("SHADOW_TRACKING_OUTCOME"),
  // SHADOW_OBSERVATION | SHADOW_TRADE_IDEA | SHADOW_WAIT | SHADOW_REJECTED
  // | SHADOW_TRACKING_OUTCOME | SHADOW_WIN | SHADOW_LOSS
  // | SHADOW_BREAKEVEN | SHADOW_EXPIRED

  pnlR:          real("pnl_r"),                       // R-multiple achieved
  resolvedAt:    timestamp("resolved_at", { withTimezone: true }),

  // ── What actually happened (filled by outcome tracker) ────────────────────
  // Prices checked at 5m, 15m, 1h, 4h after prediction
  priceAt5m:     real("price_at_5m"),
  priceAt15m:    real("price_at_15m"),
  priceAt1h:     real("price_at_1h"),
  priceAt4h:     real("price_at_4h"),
  maxFavorable:  real("max_favorable"),               // best price in direction
  maxAdverse:    real("max_adverse"),                 // worst price against direction
  tpWouldHaveHit: boolean("tp_would_have_hit"),
  slWouldHaveHit: boolean("sl_would_have_hit"),

  createdAt:     timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:     timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  shadowIdIdx:  index("sp_shadow_id_idx").on(t.shadowId),
  symbolIdx:    index("sp_symbol_idx").on(t.symbol),
  statusIdx:    index("sp_status_idx").on(t.status),
  userIdx:      index("sp_user_idx").on(t.userId),
  predictedIdx: index("sp_predicted_at_idx").on(t.predictedAt),
}));

export type ShadowPredictionRow = typeof shadowPredictionsTable.$inferSelect;
